---
- name: >-
    check_content_view_attr_repositories | Block: Handle Content Views/Composite Content Views without Repositories
  block:
    - name: >-
        check_content_view_attr_repositories | Ensure no Content Views/Composite Content Views are present
        without Repositories
      ansible.builtin.assert:
        that:
          # 'repositories' is defined for all (Composite) Content Views
          - >-
            __t_excluded_content_views |
            selectattr('repositories', 'undefined') |
            length == 0

        success_msg: All Content Views/Composite Content Views have Repositories assigned
        fail_msg: At least one Content View/Composite Content View has no Repository assigned
        quiet: "{{ _sat_quiet_assert }}"
      register: __t_has_no_repository

  always:
    - name: "check_content_view_attr_repositories | Block: Handle error case"
      when:
        - __t_has_no_repository.failed is defined
        - __t_has_no_repository.failed
      block:
        - name: >-
            check_content_view_attr_repositories | List all Content Views/Composite Content Views
            without Repositories
          ansible.builtin.debug:
            var: >-
              __t_excluded_content_views |
              selectattr(attribute='repositories', 'undefined') |
              map(attribute='name') |
              ansible.builtin.flatten

        - name: check_content_view_attr_repositories | Fail with meaningful error message
          ansible.builtin.fail:
            msg: >-
              Above Content Views/Composite Contents Views have not defined the 'repositories' attribute.
              This attribute should *always* be defined. Seeing this error indicates that the
              Satellite API response has changed and this role is no longer functional as it is.
