---
- name: >-
    check_content_view_attr_needs_publish_populated | Block: Handle Content Views/Composite Content Views which have
    needs_publish not populated
  block:

    - name: >-
        check_content_view_attr_needs_publish_populated | Ensure that all Content Views/Composite Content Views
        have the attribute 'needs_publish' populated
      ansible.builtin.assert:
        that:
          # is not None
          - >-
            __t_excluded_content_views |
            selectattr('needs_publish', '==', None) |
            length == 0

          # is boolean
          - >-
            __t_excluded_content_views |
            rejectattr('needs_publish', 'boolean') |
            length == 0

        success_msg: 'All Content Views/Composite Content Views have the attribute needs_publish populated'
        fail_msg: >-
          At least one Content View/Composite Content View does not have the attribute needs_publish
          correctly populated
        quiet: '{{ _sat_quiet_assert }}'
      register: '__t_has_needs_publish_populated'

  always:

    - name: 'check_content_view_attr_needs_publish_populated | Block: Handle error case'
      when:
        - '__t_has_needs_publish_populated.failed is defined'
        - '__t_has_needs_publish_populated.failed'
      block:

        - name: >-
            check_content_view_attr_needs_publish_populated | Collect all Content Views/Composite Content Views
            with an incorrectly populated attribute latest_version
          ansible.builtin.debug:
            var: >-
              __t_excluded_content_views |
              rejectattr('needs_publish', 'boolean') |
              map(attribute='name') |
              ansible.builtin.flatten

        - name: 'check_content_view_attr_needs_publish_populated | Fail with meaningful error message'
          ansible.builtin.fail:
            msg: >-
              Above Content Views/Composite Contents Views have not correctly populated the 'needs_publish' attribute.
              It was expected to be of boolean type, so this role cannot safely continue.
...
