---
- name: >-
    check_content_view_attr_last_published | Block: Handle Content Views/Composite Content Views which have no
    last_published attribute set
  block:

    - name: >-
        check_content_view_attr_last_published | Ensure that all Content Views/Composite Content Views have the
        attribute 'last_published' set
      ansible.builtin.assert:
        that:
          # 'last_published' is defined for all elements
          # even if a (Composite) Content View hasn't been published this attribute should exist
          - >-
            __t_excluded_content_views |
            selectattr('last_published', 'undefined') |
            length == 0

        success_msg: 'All Content Views/Composite Content Views have the attribute last_published defined'
        fail_msg: >-
          At least one Content View/Composite Content View does not have the attribute last_published defined
        quiet: '{{ _sat_quiet_assert }}'
      register: '__t_has_last_published'

  always:

    - name: 'check_content_view_attr_last_published | Block: Handle error case'
      when:
        - '__t_has_last_published.failed is defined'
        - '__t_has_last_published.failed'
      block:

        - name: >-
            check_content_view_attr_last_published | List all Content Views/Composite Content Views
            without attribute last_published
          ansible.builtin.debug:
            var: >-
              __t_excluded_content_views |
              selectattr('last_published', 'undefined')

        - name: 'check_content_view_attr_last_published | Fail with meaningful error message'
          ansible.builtin.fail:
            msg: >-
              Above Content Views/Composite Contents views have not defined the 'last_published' attribute.
              This attribute should *always* be defined, even when the Content View/Composite Content View has not
              been published yet.
...
