---
- name: >-
    content_view_exclusion | Exclude Content Views/Composite Content Views from the API results which are not defined in
    _satellite_content_views or are excluded
  ansible.builtin.set_fact:
    # we first check if __t_reject_content_views is defined and contains elements
    #
    # if __t_reject_content_views contains elements:
    # - reject any (Composite) Content Views which are excluded via __t_reject_content_views
    # - reject any (Composite) Content Views which have specified 'patch_day_exclude: true' in their definition
    # - select all (Composite) Content Views which are defined in _satellite_content_views
    #
    # If __t_reject_content_views does not contain elements:
    # - reject any (Composite) Content Views which have specified 'patch_day_exclude: true' in their definition
    # - select all (Composite) Content Views which are defined in _satellite_content_views
    __t_excluded_content_views: >-
      {{
        (
          __t_reject_content_views is defined
          and __t_reject_content_views != None
          and __t_reject_content_views | length > 0
        ) | ansible.builtin.ternary(

          __t_content_views.resources |
          rejectattr('name', 'in', __t_reject_content_views) |
          rejectattr('name', 'in',
            _satellite_content_views |
            selectattr('patch_day_exclude', 'defined') |
            selectattr('patch_day_exclude', '==', true) |
            map(attribute='name')
          ) |
          selectattr('name', 'in',
            _satellite_content_views | map(attribute='name')
          ),

          __t_content_views.resources |
          rejectattr('name', 'in',
            _satellite_content_views |
            selectattr('patch_day_exclude', 'defined') |
            selectattr('patch_day_exclude', '==', true) |
            map(attribute='name')
          ) |
          selectattr('name', 'in',
            _satellite_content_views | map(attribute='name')
          )
        )
      }}

    # empty unused variable again
    __t_content_views: {}

- name: 'content_view_exclusion | Debug: __t_excluded_content_views (name only)'
  ansible.builtin.debug:
    var: "__t_excluded_content_views | map(attribute='name')"
    verbosity: 1

- name: 'content_view_exclusion | Debug: __t_excluded_content_views'
  ansible.builtin.debug:
    var: "__t_excluded_content_views | map(attribute='name')"
    verbosity: 2
...
